### ISSUE TITLE
compiling samtools/htslib

### ISSUE THREAD

**Issue by jerowe** [phusion/holy-build-box#1]
Hello,

This isn't so much an issue as a cry for help.

I'm trying to compile htslib from samtools [http://www.htslib.org/download/](here), and I'm getting an error on htslib. In general I'm hoping to use holy-build-box to build bioinformaitcs software.

if test -n "/io/binary/libexec/htslib"; then mkdir -p -m 755 /io/binary/libexec/htslib; fi
gcc -shared -Wl,-soname,libhts.so.1 -pthread -L/hbb_exe -static-libstdc++ -rdynamic -o libhts.so kfunc.pico knetfile.pico kstring.pico bgzf.pico faidx.pico hfile.pico hfile_net.pico hts.pico md5.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico cram/thread_pool.pico cram/vlen.pico cram/zfio.pico plugin.pico -lz -lm -ldl 
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-CentOS-linux/4.8.2/ld: /hbb_exe/lib/libz.a(crc32.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/hbb_exe/lib/libz.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status

Any insight would be very appreciated!

Best,
Jillian

**Comment by FooBarWidget** [comment]
As the error message says, you need -fPIC. You are using the 'exe' variant which doesn't compile the libraries with -fPIC. Use one of the other variants that do compile the libraries with -fPIC.
