### ISSUE TITLE
Cannot start HBB in Arch Linux with kernel 4.20.11

### ISSUE THREAD

**Issue by FreddieChopin** [phusion/holy-build-box#12]
When running the basic command presented in the tutorials:

`$ docker run -t -i --rm phusion/holy-build-box-64:latest bash`

absolutely nothing happens, the command quits in about ~10 seconds with exit code 139 and `docker ps -a` displays nothing.

When trying the most simple command:

```
$ docker run phusion/holy-build-box-64:latest
$ docker ps -a
CONTAINER ID        IMAGE                                          COMMAND                  CREATED             STATUS                        PORTS               NAMES
6657c56132f3        phusion/holy-build-box-64:latest               "/bin/bash"              10 seconds ago      Exited (139) 7 seconds ago                        affectionate_bell
```

Any idea how to solve this? I'm not a docker expert (;

**Comment by rphillips** [comment]
Looks like bash is crashing with:

```
[17724.098428] bash[10046] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7ffdfda90578 ax:ffffffffff600400 si:7ffdfda90f71 di:0
[17724.098433] bash[10046]: segfault at ffffffffff600400 ip ffffffffff600400 sp 00007ffdfda90578 error 15
```

**Comment by rphillips** [comment]
Adding this to the grub commandline fixed it for me: https://github.com/docker/for-linux/issues/58#issuecomment-315150740

**Comment by FooBarWidget** [comment]
Looks like this is only an issue as long as we use CentOS 6. There are plans to migrate to CentOS 7 (#27), so I expect this issue to be obsolete soon.
