### ISSUE TITLE
Maintainers wanted?

### ISSUE THREAD

**Issue by nightlark** [phusion/holy-build-box#16]
Hi! First off, thanks! This docker container is awesome, basically exactly what we needed to automate building some binaries for releases that work on a wider range of Linux systems (there were some minor issues like a bug in gcc 7.3.1 that were easy to work around).

I noticed the readme has a maintainers wanted badge -- what do you need help with? It looks like having a CentOS 6 container will be needed for the foreseeable future and I'd rather help keep an existing project up to date than create and maintain a fork.

**Comment by FooBarWidget** [comment]
Hi. Yes new maintainers would definitely be welcome.

We need help with keeping the issue tracker clean, with reviewing pull requests, and basically keeping this project working. If new maintainers have a vision for where the project should head to, then that's welcome too.

**Comment by nightlark** [comment]
Okay! It does seem like there are a few issues and PRs that can be cleaned up.

Some of the changes I’ve made (https://github.com/build-environment/holy-build-box) are updating to a newer compiler toolset (for a particularly annoying compiler bug fix), updating CMake, installing a recent version of git, and automated Docker image builds and uploads to Docker Hub.

It seems like this would be a really useful base image to use with something like GitHub Actions for projects to automate release builds for Linux binaries (part of the motivation for adding a recent version of git).

**Comment by FooBarWidget** [comment]
Yes a proper CI would definitely help.

Would you like to have commit access in order to help out?

**Comment by nightlark** [comment]
Yea, commit access would probably be the easiest way to get started with going through issues/PRs and merging in the changes from my fork (if you're okay with them).

For setting up CI with automated pushes to DockerHub, in my fork I have it set up with two secrets for GitHub Actions with my DockerHub username and personal access token (basically equivalent to an account password, so there are some security implications if it ever gets out).

For a similar setup here it could either push to phusion/holy-build-box-* depending on how comfortable you are with having GitHub store a docker hub token. Or it could be set up with the docker hub credentials I'm using to push to ([buildenvironments/holy-build-box-64](https://hub.docker.com/repository/docker/buildenvironments/holy-build-box-64) -- either with the maintain permission level (if it's able to add secrets for GitHub actions) or by sending you the username/token.

**Comment by FooBarWidget** [comment]
I'm comfortable with storing Docker Hub tokens on Github as secrets.

Could you provide me with your Docker Hub ID? I'll add you as a collaborator to phusion/holy-build-box-*.

**Comment by nightlark** [comment]
My Docker Hub ID is rmast.

**Comment by FooBarWidget** [comment]
All right, I've added you to both Docker Hub and to this Github project. Thanks for volunteering!
