### ISSUE TITLE
std::thread support not present in /hbb_exe/lib/libstdc++.a

### ISSUE THREAD

**Issue by kerrmattabcorp** [phusion/holy-build-box#19]
Not too sure about this one, but I have a C++ application that I'm building with holy-build-box. I'm having an issue when trying to link code that uses std::call_once:
...
/opt/rh/devtoolset-8/root/usr/include/c++/8/mutex:677: undefined reference to `std::__once_call'
...

It appears the /hbb_exe/lib/libstdc++.a may not have thread support, compare:

nm -C /hbb_exe/lib/libstdc++.a | grep std::thread
and
nm -C /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++.a | grep std::thread
nm: compatibility-debug_list-2.o: no symbols

**Comment by nightlark** [comment]
Hi! Do you have a minimal example that gives the error? Also, which Docker image are you using?

**Comment by nightlark** [comment]
Actually, a 3rd question, did you make sure to either use `hbb-exec` or `source /hbb_exe/activate`?

Some useful docs on those can be found on these two pages:
https://github.com/phusion/holy-build-box/blob/master/TUTORIAL-1-BASICS.md#holy-build-box-environment-activation
https://github.com/phusion/holy-build-box/blob/master/ENVIRONMENT-STRUCTURE.md

**Comment by kerrmattabcorp** [comment]
So basically just a cut down use of std::call_once as per the example on cppreference:

#include <thread>
#include <mutex>
#include <iostream>

std::once_flag flag1;

void simple_do_once()
{
    std::call_once(flag1, [](){ std::cout << "Simple example: called once\n"; });
} 

int main()
{
    std::thread st1(simple_do_once);
    std::thread st2(simple_do_once);
    st1.join();
    st2.join();
}

using the latest build (2.0.1 with the gcc8 toolchain) compile with:
source /hbb_exe/activate
g++ /tmp/tt.cpp -o /tmp/test -lpthread # <--- this works dynamically linking stdlib
g++ -static-libstdc++ /tmp/tt.cpp -o /tmp/test -lpthread # <--- this works static link but picks up libstdc++.a from /opt/rh/devtoolset-8
g++ -L/hbb_exe/lib/ -static-libstdc++ /tmp/tt.cpp -o /tmp/test -lpthread # <---- this fails to link

**Comment by nightlark** [comment]
Is there a reason you're trying to link to the copy in `/hbb_exe/lib` instead of `/opt/rh/devtoolset-8`? It looks like the hbb activate functions are intended to make the libstdc++ provided by devtoolset-8 be the one used for linking.

I wouldn't be surprised if whatever copy of libstdc++ is in /hbb_exec/lib is something horribly outdated, maybe the default provided by CentOS 6.

**Comment by kerrmattabcorp** [comment]
I wasn't intentionally, I had assumed it was because of the LDFLAGS etc env vars that the activate sets up? I originally hit this when using CMake on a pretty large app and -L/hbb_exe/lib was added for me.

My initial "work-around" was to simply overwrite the /hbb_exe/lib version with the one from the toolset which works fine it seems

**Comment by kerrmattabcorp** [comment]
It might just be a dodgy CMake definition... (I have to go now -- I'll check back in tomorrow - thanks for swift responses!)

**Comment by nightlark** [comment]
Ah okay, I haven't run into this issue with the CMake project I have that uses std::threads, so it could be... though looking at where [hbb builds libstdc++](https://github.com/phusion/holy-build-box/blob/master/image/build.sh#L383-L391), it seems like it is intended to be a pretty recent copy of libstdc++.

Looking through the PRs, I found [this old one about C++11 threads](https://github.com/phusion/holy-build-box/pull/4/files). If you've got some time and can confirm that the PR fixes the threading issue, I'll merge it in.

**Comment by kerrmattabcorp** [comment]
Hi, I definitely think that I'm encountering the issue identified in that PR. Unfortunately for me the PR as it stands didn't fix the issue for me -- (maybe the v8 toolchain has changed things?). Running configure for libgcc didn't result in gthr-default.h being created. What I did try was simply copying ${gcc_src_root}/libgcc/gthr-posix.h to ${gcc_src_root}/libgcc/gthr-default.h and then running configure && make for libstdc++v3 and that seems to work.

I've wrestled with gcc a bit this morning trying to "do it properly" but it's a bit daunting trying to understand to correct procedure.

**Comment by nightlark** [comment]
It looks like this thread might be relevant: http://gcc.1065356.n8.nabble.com/PATCH-libstdc-Fix-missing-gthr-default-h-issue-on-libstdc-configure-td875564.html

My impression is that the patch wasn't applied because no one would want to build libstdc++ without also building gcc/libgcc.

**Comment by FooBarWidget** [comment]
Linking to the libstdc++ provided by Holy Build Box, rather than the one provided by devtoolset-8, is intentional. From LINKING-CXX.md:

> Holy Build Box ships static libstdc++ libraries that are compiled with `-fvisibility=hidden`, so symbol clashes do not occur.

This is why we ship 3 versions of libstdc++.a:
/hbb_shlib/lib/libstdc++.a
/hbb_exe_gc_hardened/lib/libstdc++.a
/hbb_exe/lib/libstdc++.a

So yes, this is a bug that needs to be fixed.

**Comment by FooBarWidget** [comment]
Upon inspecting the libstdc++ source code, it seems that std::thread support is disabled because the `configure` script failed to detect gthreads (gthr.h). Gthreads appears to be something that's part of libgcc.

The plot thickens.

**Comment by FooBarWidget** [comment]
I think it's probably caused by the fact that we try to compile libstdc++ without the rest of gcc. Its configure script tries to find gthr.h in ../libgcc, but it isn't there. This appears to be a bug in the libstdc++ build system.

But gthr.h *is* in libstdc++'s include/bits subdirectory. So adding -Iinclude/bits to CXXFLAGS fixed it.
