### ISSUE TITLE
After transferring the binary, the error: segmentation fault

### ISSUE THREAD

**Issue by valentin6work** [phusion/holy-build-box#21]
For the test, I use an example from their documentation [ https://github.com/phusion/holy-build-box/blob/master/TUTORIAL-1-BASICS.md](url) Compilation is performed on the Ubuntu + Docker virtual machine. After compilation, launch on Ubuntu goes fine, everything works. When migrating to another Linux host (CentOS), when starting the binary, I get an error: **segmentation fault**. What needs to be done to make this binary work normally?

**Comment by FooBarWidget** [comment]
@valentin6work is this issue still relevant?

**Comment by valentin6work** [comment]
FooBarWidget @valentin6work is this issue still relevant? - yes

**Comment by FooBarWidget** [comment]
Can you try Holy Build Box 3? It upgraded to CentOS 7, does that still produce crashing binaries? If so, can you post more details about the crash?
