### ISSUE TITLE
Phusion PackageCloud repo will go away / drop x86 / upgrade to CentOS 7

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/holy-build-box#27]
The build script references https://packagecloud.io/install/repositories/phusion/centos-6-scl-i386/script.rpm.sh, but this repository will go away in less than a year.

I think we should either drop x86 support altogether, or find an alternative. I think dropping x86 isn't so crazy nowadays: even years ago, I've observed that nearly nobody uses the x86 binaries for Passenger. I think that going forward, we're more likely to want to support arm64 instead.

**Comment by nightlark** [comment]
The download info I've seen for other packages lines up with x86 not being used much. Yea, now that Apple has switched to arm64, I imagine we will start to see a lot more arm-based laptops and desktops coming out soon.

The only alternative I can think of would be building the devtoolset from source. As it is right now, the x86 image only has devtoolset-7 installed and no one has said they need a newer version. I'd be inclined to update packages like git and release a final image for x86.

I think for arm64 support, updating from CentOS 6 to 7 will make sense. So maybe a final release of a CentOS 6 x64 image with devtoolset-9 to avoid users having issues with unsupported C++ features for as long as possible.

**Comment by FooBarWidget** [comment]
I also think upgrading to CentOS 7 makes sense. From a compatibility standpoint, RHEL 7 is already 7 years old (late 2013). Now that RHEL 8 has been out for a while, I think CentOS 7 level binary compatibility is old enough to support all the commonly in-use Linux distros nowadays.
