### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by adomasbaliuka** [phusion/holy-build-box#64]
The GitHub actions have been failing for a year now.

I also don't know where to find the old logs of past successful CI runs. If those were available, one might have a better chance to find and fix the issue...

**Comment by nightlark** [comment]
It looks like the amd64 Docker image builds successfully, then it's failing to use buildx to build the arm64 variant. The exec error makes me think there is a mismatch between the CPU architecture of the runner and the base centos:7 image being used -- such as using the amd64 variant of the centos:7 image on an (emulated) arm64 cpu for the build. Or using the arm64 centos:7 image, but trying to run it on the host amd64 cpu.

Maybe qemu needs to be installed first as part of the CI workflow.
