### ISSUE TITLE
Q: Are very recent distributions really supported?

### ISSUE THREAD

**Issue by ilg-ul** [phusion/holy-build-box#7]
The FAQ states that binaries should be ok on Debian >6, Ubuntu >10, which would be great.

The question is if binaries were really tested on very new distributions, like ARCH, which is probably the most advanced one. And even Ubuntu 16/17.

**Comment by FooBarWidget** [comment]
The most recent distro I've tested on is Ubuntu 16.04.

It should work on even newer ones. I've never heard of glibc or the Linux kernel breaking backward compatibility.

**Comment by ilg-ul** [comment]
And if a certain build requires a newer version of some tools (for example the gcc/binutils configures require a specific version of automake), the solution is to compile it and install in a separate location, which is in the path before the system (very old) tools?

**Comment by FooBarWidget** [comment]
Yes.

**Comment by ilg-ul** [comment]
ok, thank you.
